services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml_app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}  # Cambia 'localhost' a 'db'
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}

  db:
    image: postgres:13
    container_name: ml_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"  # Asegúrate de que el puerto sea 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: